apiVersion: tpokki.github.com/v1alpha1
kind: GatlingTask
metadata:
  name: example-gatlingtask
spec:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 500M
    requests:
      cpu: 200m
      memory: 500M
  scenario:
    name: Example
    git:
      repo: https://github.com/tpokki/gatling-operator.git
      directory: examples/scenario/
